name: CypressToDo Tests

on: 
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0 
        with:
           browser: chrome
           command: npm run test
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          # Artifact name
          name: MyReport
          # A file, directory or wildcard pattern that describes what to upload
          path: cypress/reports/html
          retention-days: 30
      - name: Slack Notification
        uses: rtCamp/action-slck-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Sajid
          SLACK_TITLE: Regression Test
          SLACK_COLOR: ${{ job.status }}      