name: CypressToDo Tests

on: 
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v4.1.2
      - name: Cypress.io
      - uses: cypress-io/github-action@v6.5.0
          
