name: CypressToDo Tests

on: 
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v4.1.2
      - name: Setup Node.js environment
      - uses: actions/setup-node@v4.0.2
        with:
          # Set always-auth in npmrc.
          cache: "npm"
          run: "test"
          
